### ISSUE TITLE
主题部署到Github失败

### ISSUE THREAD

**Issue by tianheg** [wujun234/hexo-theme-tree#10]
部署到 Github 后，点击网址：https://gaotianhe.github.io/knowledge/  。

发现页面没有渲染，只有文本。我把你的博客下载后放到 public 文件夹里，发现 404 了。

**Comment by tianheg** [comment]
我知道是怎么回事了，只能部署到网址：https://gaotianhe.github.io/。

不能有其他指向，不过我记得以前是可以指向子路径的啊，可能跟这个有区别

我成功部署到了 我的 gitee 网址 http://gaotianhe.gitee.io

是可以部署到子路径的，不过需要在本地的根目录的 _config.yml 文件修改 
```
url: http://yoursite.com
root: /
```

而我没有修改。

**Comment by wujun234** [comment]
这个是 GitHub Pages 的限制，个人页面只能是根路径，组织或者项目页面才可以子路径

yidajiabei <notifications@github.com> 于2020年4月23日周四 上午9:59写道：

**Comment by tianheg** [comment]
不过，可以通过修改 hexo 的配置使用子路径
