### ISSUE TITLE
markdown-it的使用配置方法

### ISSUE THREAD

**Issue by BeenStone01** [wujun234/hexo-theme-tree#11]
懂的不多，使用方法中markdown-it的配置使用能否介绍的详细点？
转去官网两个命令安装后（
npm install markdown-it --save
bower install markdown-it --save)
效果：https://beenstone01.github.io/2020/04/23/hello-world/
就不知道接下来怎么操作了……烦请斧正，谢谢。

**Comment by BeenStone01** [comment]
效果：https://beenstone01.github.io/2020/04/23/hello-world/

**Comment by wujun234** [comment]
hi，看你的页面，感觉效果出来了呀？

我也是网上看的教程，大概像下面这类：

https://titangene.github.io/article/hexo-markdown-it.html

**Comment by BeenStone01** [comment]
是的，也是莫名其妙，昨晚弄到很晚，没有成功……目前没有发现更好的笔记主题，所以誓要把它搞出来……，所以今天弄了一会儿，还没效果，就不想耗时了，之前发现c++代码渲染不出来，后来可以了。

最后谢谢你的热心回复。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: WuJun<mailto:notifications@github.com>
发送时间: 2020年4月24日 11:17
收件人: wujun234/hexo-theme-tree<mailto:hexo-theme-tree@noreply.github.com>
抄送: Been Stone<mailto:beenstone@msn.cn>; Author<mailto:author@noreply.github.com>
主题: Re: [wujun234/hexo-theme-tree] markdown-it的使用配置方法 (#11)


hi，看你的页面，感觉效果出来了呀？

我也是网上看的教程，大概像下面这类：

https://titangene.github.io/article/hexo-markdown-it.html

―

**Comment by wujun234** [comment]
可能是缓存的锅，下次试试 hexo clean 有奇效
