### ISSUE TITLE
上一篇和下一篇方向相反

### ISSUE THREAD

**Issue by hellomyheart** [wujun234/hexo-theme-tree#12]
文章的最后上一篇和下一篇方向是相反的，左边是下一篇，右边是上一篇。我以为是模板里面写反了，把模板里面next和pre互换了位置，结果还是反的，不知道什么原因。

**Comment by wujun234** [comment]
严格来说他不是反的，只是它是按照全体的发布时间来排序的，不是按照目录顺序排序的
