### ISSUE TITLE
显示公式问题

### ISSUE THREAD

**Issue by ruyiluo** [wujun234/hexo-theme-tree#14]
老哥，你这个主题真的太棒了，但是无法显示markdown的公式，这个该怎么解决呀？

**Comment by MTCai** [comment]
https://www.cnblogs.com/zhyantao/p/10424874.html

**Comment by PabloLION** [comment]
md渲染是hexo的问题，不是该主题的问题。
我换了渲染器:https://github.com/niemingzhao/hexo-renderer-markdown

**Comment by seekstar** [comment]
也可以用hexo-filter-mathjax + hexo-renderer-pandoc，亲测有效。详细教程：<https://seekstar.github.io/2021/11/16/hexo%E6%94%AF%E6%8C%81latex%E9%A3%8E%E6%A0%BC%E7%9A%84%E5%85%AC%E5%BC%8F%E7%BC%96%E8%BE%91/>
