### ISSUE TITLE
侧栏不弹出

### ISSUE THREAD

**Issue by PabloLION** [wujun234/hexo-theme-tree#15]
我是github新手。
这是我目前的site.category列表：
Ability-Language-English
Computer-Hardware
Computer-Web-Blog
MAIN
Tool
计算机-a
我的侧栏点击的时候不弹出。
欢迎远程调试。

另外，求问ejs用什么IDE能让格式好看一点？我用的VScode，试了很多插件也不能识别ejs for，总是把缩进取消。google也没找到。

**Comment by Pablion** [comment]
在sidebar.ejs的第14行
var chain = post.slug.split("/");
post.slug是什么？我在Hexo的Doc中没找到。

**Comment by wujun234** [comment]
我直接用的 notepad++，侧栏点击你打开浏览器 console 看看有没有什么报错

**Comment by wujun234** [comment]
[image: image.png]
https://hexo.io/api/posts.html


Pablion <notifications@github.com> 于2020年6月28日周日 上午1:16写道：

**Comment by PabloLION** [comment]
您好。谢谢老哥回复。
我之前已经看过了：
PowerShell中无报错；
浏览器Console里只有一个chrome插件的warning。没有error。

我的front-matter是这么写的：

```
---
title: This Website
date: 2020-06-23 06:50:02
category: Computer-Web-Blog
tags:
---
```

所有.md文件的路径都是
`%ROOT%\source\_posts`

点击展开sidebar按钮时，sidebar的图标也不会变成X。
在sidebar.ejs中`console.log(pathToTree(site.posts))`，PowerShell输出`undefined`。

**Comment by wujun234** [comment]
是按目录作为侧边栏的

发自我的iPhone

**Comment by PabloLION** [comment]
按文件的目录吗？我看到使用的是slug属性，所以试了：
- 放在`source\_post`下；
- 放在`source\somefolder\_post`下；
- 放在`source\_post\somefolder`下；
都没有效果。

我把`sidebar.ejs`移动到了其他的主题下，能够正确显示帖子的题目和分类了。但是在tree下不能。

**Comment by wujun234** [comment]
你看看hexo编译的时候有没有报错吧

**Comment by PabloLION** [comment]
> 你看看hexo编译的时候有没有报错吧

看过了，没有报错。
我在我的网站中直接在 ejs文件中的`<div id="sidebar">`标签中添加`class="on"`，就能打开和显示侧栏了。 
但是仍然关不上。我准备看看js

**Comment by PabloLION** [comment]
我感觉我找到问题了：
`hexo generate`之后，生成的`public\js\main.js`，和`themes\tree\source\js\main.js`完全不一样。里面没有定义函数，因此不会打开侧栏。
这是hexo的问题？还是我设置的问题？

我在Chrome里面已经开启了 `disable cache` ， 也重新`hexo generate`了，和之前一样。
然后我试过把 main.js放到`script`文件夹下，会报错。

--------

发现是在hexo根目录下的_config.yml中，我写有`# theme: wixo`,虽然注释掉了，但是还是会尝试读取wixo中的`main.js.`，虽然用的相关ejs是tree中的。
```console
ERROR Asset render failed: js/main.js
Error: ENOENT: no such file or directory, open 'D:\hexo\Pablion\themes\wixo\source\js\main.js'
```
能确认Hexo的问题了。
我之前看到有人说过，说hexo对`_config.yml`文件的变动不敏感。
现在情况是，Hexo检测到theme变化了，但是还用变化之前的main.js 。这个bug应该怎样报告给Hexo?

**Comment by wujun234** [comment]
你再按文档看看吧，可能有啥没走对，目前没别人遇到这个问题

发自我的iPhone

**Comment by PabloLION** [comment]
OK. 反正现在这个问题已经解决了。只要知道这里有个坑就行了。
