### ISSUE TITLE
半角标点渲染

### ISSUE THREAD

**Issue by PabloLION** [wujun234/hexo-theme-tree#17]
`'`和`"`会被渲染成全角字符`’`和`”`， 在默认的字体下占两个字符宽度。

**Comment by wujun234** [comment]
> `'`和`"`会被渲染成全角字符`’`和`”`， 在默认的字体下占两个字符宽度。

![image](https://user-images.githubusercontent.com/7530593/86784041-a342a200-c093-11ea-80d1-b11cebf8f74b.png)

我看是 ok 的啊？你再确定一下？

**Comment by PabloLION** [comment]
虽然没有确认，我猜测是我md渲染器的问题。
