### ISSUE TITLE
在手机上看，回到顶部按钮不好使

### ISSUE THREAD

**Issue by Shmilyqjj** [wujun234/hexo-theme-tree#18]
手机上看-回到顶部按钮不好使

**Comment by Shmilyqjj** [comment]
还有，可以加个关灯开灯的按钮嘛，看文章有时候晚上看可能灰色或者深色背景比较好点

**Comment by Shmilyqjj** [comment]
> 还有，可以加个关灯开灯的按钮嘛，看文章有时候晚上看可能灰色或者深色背景比较好点
https://shen-yu.gitee.io/  像这个一样

**Comment by wujun234** [comment]
我试了是好使的啊？你是哪个页面不行？

夜间模式考虑下有没有必要哈，因为我都是用的浏览器的阅读模式调亮度😂

周末看看吧，好久没碰了

发自我的iPhone

**Comment by Shmilyqjj** [comment]
> 我试了是好使的啊？你是哪个页面不行？ 夜间模式考虑下有没有必要哈，因为我都是用的浏览器的阅读模式调亮度 周末看看吧，好久没碰了 发自我的iPhone
> […](#)

用了华为浏览器，X浏览器和微信自带浏览器，那个按钮都不能用。

**Comment by wujun234** [comment]
微信自带浏览器我试了OK，考虑一下是不是有js没加载？临时被墙了？

发自我的iPhone
