### ISSUE TITLE
还是代码块问题

### ISSUE THREAD

**Issue by zhihancn** [wujun234/hexo-theme-tree#19]
老哥主题设置很棒，很简约

代码块没有语法高亮，能解决么？

之前有issue说是用第三方插件？有的话请指路，能否有好的代码主题插件推荐？

**Comment by wujun234** [comment]
https://github.com/wujun234/hexo-theme-tree#%E6%8E%A8%E8%8D%90%E6%8F%92%E4%BB%B6 readme 里有写我用的 markdown 插件  `Markdown-it` ，我没试过其它的

**Comment by wujun234** [comment]
#59
