### ISSUE TITLE
如何实现全文搜索？

### ISSUE THREAD

**Issue by chinobing** [wujun234/hexo-theme-tree#2]
能不能以某关键字作为开头，实现全文搜索或者标题搜索？

**Comment by wujun234** [comment]
> 
> 
> 能不能以某关键字作为开头，实现全文搜索或者标题搜索？

现在的搜索就是基于标题的啊？全文搜索还没加

**Comment by chinobing** [comment]
对，标题搜索已经实现了，希望以后可以加入全文搜索，因为我对这个主题一见如故，找了这么久终于发现一个是用来记录笔记且有目录树导航的主题，感谢作者你开源。

**Comment by wujun234** [comment]
嗯嗯，感谢你的喜欢，记下来了，过阵子不忙了就给全文搜索加上
