### ISSUE TITLE
代码无法自动换行

### ISSUE THREAD

**Issue by x7peeps** [wujun234/hexo-theme-tree#20]
code部分无法自动换行，

**Comment by wujun234** [comment]
代码格式化我也是用的第三方插件，找时间换一个更好的

**Comment by x7peeps** [comment]
目前你的博客的代码插件是否可以有个教程教教呢

**Comment by wujun234** [comment]
> 目前你的博客的代码插件是否可以有个教程教教呢

看看 readme 哦，里面有链接到官方文档

https://github.com/wujun234/hexo-theme-tree#%E6%8E%A8%E8%8D%90%E6%8F%92%E4%BB%B6

**Comment by wujun234** [comment]
#59
