### ISSUE TITLE
添加mermaid 思维导图

### ISSUE THREAD

**Issue by s1g0day** [wujun234/hexo-theme-tree#21]
1.安装插件
npm install hexo-filter-mermaid-diagrams

2.编辑配置文件
编辑/thems/tree/_config.yml，在 _config.yml 的最后加上以下内容，在根目录下写不写没有影响
```
# mermaid chart
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  version: "7.1.2" # default v7.1.2
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    #startOnload: true  // default true
```

3.引入js文件
找到主题里面的页脚文件，也即 themes/tree/layout/_partials/footer.ejs ，在文件最后加上以下内容
```
<% if (theme.mermaid.enable) { %>
  <script src='https://unpkg.com/mermaid@<%= theme.mermaid.version %>/dist/mermaid.min.js'></script>
  <script>
    if (window.mermaid) {
      mermaid.initialize({theme: 'forest'});
    }
  </script>
<% } %>
```

添加之后一定是成功的，但预览时可能会发现编写的思维导图代码仍然是源代码，这个问题的原因可能是由于缓存问题或者加载的比较慢，大哥们有没有解决方法

**Comment by wujun234** [comment]
本地成功过么？

**Comment by s1g0day** [comment]
> 本地成功过么？

本地成功了，只不过有时候思维导图不能完全加载，需要多刷新几下就好

**Comment by wujun234** [comment]
> > 本地成功过么？
> 
> 本地成功了，只不过有时候思维导图不能完全加载，需要多刷新几下就好

会不会因为 js 下载比较慢？你把 mermaid.min.js 添加到本地试试？

**Comment by s1g0day** [comment]
> > > 本地成功过么？
> > 
> > 
> > 本地成功了，只不过有时候思维导图不能完全加载，需要多刷新几下就好
> 
> 会不会因为 js 下载比较慢？你把 mermaid.min.js 添加到本地试试？

今天尝试了一下，如果用mermaid多的话还是会有一些加载不下来，需要多刷新几次。
可能是hexo本身的问题，只能以后少用点了😂

**Comment by wujun234** [comment]
> > > > 本地成功过么？
> > > 
> > > 
> > > 本地成功了，只不过有时候思维导图不能完全加载，需要多刷新几下就好
> > 
> > 
> > 会不会因为 js 下载比较慢？你把 mermaid.min.js 添加到本地试试？
> 
> 今天尝试了一下，如果用mermaid多的话还是会有一些加载不下来，需要多刷新几次。
> 可能是hexo本身的问题，只能以后少用点了😂

可能是渲染太慢了
