### ISSUE TITLE
請問能自動展開樹嗎？

### ISSUE THREAD

**Issue by fatfingererr** [wujun234/hexo-theme-tree#22]
作者你好，我已經搜索過問題，似乎沒有人提問到。
請問我因為資料比較少，但仍然有樹的結構，請問我有辦法預設讓樹展開嗎？
若是微調的話，可否能給我一些建議呢？

**Comment by wujun234** [comment]
目录树的代码是写在这个路径的： \themes\tree\layout\_partial\sidebar.ejs

你把
```
<div class="article-toc" style="display: none;"></div>
```
替换为
```
<div class="article-toc" style="display: block;"></div>
```
试试看 ok 不

**Comment by fatfingererr** [comment]
看起來好像沒有, 但沒關係, 我目前應該可以用目錄頁來解決這個問題, 不用展開了, 謝謝你!
