### ISSUE TITLE
关于全文搜索

### ISSUE THREAD

**Issue by GaHoWong** [wujun234/hexo-theme-tree#24]
如果这个主题拥有全文搜索的话，就完美了。知识点太多，我有时候只想到关键字，如果标题没有关键字，基本搜索不到。

**Comment by wujun234** [comment]
我看一般这种静态网站的搜索，都是用主流搜索引擎加site关键字搞的，加个todo

**Comment by chinobing** [comment]
> 如果这个主题拥有全文搜索的话，就完美了。知识点太多，我有时候只想到关键字，如果标题没有关键字，基本搜索不到。

可以自己添加插件，我也是这样做的。 参考next主题的搜索插件，他家是点击了才加载json，这样就不拖慢网站加载

**Comment by wujun234** [comment]
新增了基于搜索引擎的全站搜索，可以刷新一下看看demo，https://github.com/wujun234/hexo-theme-tree#6-%E5%85%A8%E7%AB%99%E6%90%9C%E7%B4%A2

**Comment by GaHoWong** [comment]
> > 如果这个主题拥有全文搜索的话，就完美了。知识点太多，我有时候只想到关键字，如果标题没有关键字，基本搜索不到。
> 
> 可以自己添加插件，我也是这样做的。 参考next主题的搜索插件，他家是点击了才加载json，这样就不拖慢网站加载

请问是Algolia搜索插件吗？

**Comment by chinobing** [comment]
> > > 如果这个主题拥有全文搜索的话，就完美了。知识点太多，我有时候只想到关键字，如果标题没有关键字，基本搜索不到。
> > 
> > 
> > 可以自己添加插件，我也是这样做的。 参考next主题的搜索插件，他家是点击了才加载json，这样就不拖慢网站加载
> 
> 请问是Algolia搜索插件吗？

不是，是利用了hexo的search插件`npm install hexo-generator-search --save`生成xml文件， [我仓库的hexo-theme-tree](https://github.com/chinobing/hexo-theme-tree)已改为带全文搜索的，不过样式什么的都没有优化，我觉得wujun234后期改用的google搜索比较好
