### ISSUE TITLE
本地图支持问题

### ISSUE THREAD

**Issue by yangxuehang** [wujun234/hexo-theme-tree#29]
是否支持本地图？我尝试在md中添加_post目录下的图，但是有问题。

**Comment by wujun234** [comment]
支持啊，我的图都是本地的，你注意下路径

**Comment by yangxuehang** [comment]
> 支持啊，我的图都是本地的，你注意下路径

谢谢你的回复。能举例说明一下如何注意路径吗？我试了下没成功。

我在_post 下 新建了 "日记“，在”日记“里写的test.md，图片img.png 也是在"日记"下面。相对路径直接引用，也存在问题。

**Comment by wujun234** [comment]
要放在_post外面

发自我的iPhone

**Comment by yangxuehang** [comment]
谢谢回复！已搞定。
原因是HEXO配置文件 _config.yml中的post_asset_folder属性没有进行配置。配置后就ok了。
