### ISSUE TITLE
复制md文档问题

### ISSUE THREAD

**Issue by qs-lll** [wujun234/hexo-theme-tree#3]
Cannot read property 'charCodeAt' of undefined
    at eval (/Users/qs/Documents/CoreTxt/Blog/themes/tree/layout/_partial/sidebar.ejs:57:25)
    at Array.sort (native)
    at showTree (/Users/qs/Documents/CoreTxt/Blog/themes/tree/layout/_partial/sidebar.ejs:54:12)
    at eval (/Users/qs/Documents/CoreTxt/Blog/themes/tree/layout/_partial/sidebar.ejs:90:17)
    at Array.forEach (<anonymous>)
    at showTree (/Users/qs/Documents/CoreTxt/Blog/themes/tree/layout/_partial/sidebar.ejs:63:12)
    at eval (/Users/qs/Documents/CoreTxt/Blog/themes/tree/layout/_partial/sidebar.ejs:98:5)

-------------
你应该写个demo 
方便我这样的新手使用,实不相瞒 我搞了两三个小时才把文件归档搞明白 ,,

**Comment by qs-lll** [comment]
问题定位到charCodeAt() 解决好了 麻烦@一下我  js代码实在是玩不来啊

**Comment by wujun234** [comment]
排序有个小 bug，改了

你说的 demo 是指啥？主体下载下来就能用啊…… @qs-lll

**Comment by chinobing** [comment]
> 
> 
> 排序有个小 bug，改了
> 
> 你说的 demo 是指啥？主体下载下来就能用啊…… @qs-lll

文章或文件夹排序是根据什么来决定的？能改不？

**Comment by wujun234** [comment]
> 
> 
> > 排序有个小 bug，改了
> > 你说的 demo 是指啥？主体下载下来就能用啊…… @qs-lll
> 
> 文章或文件夹排序是根据什么来决定的？能改不？

按 tile ascii 排序的，要修改去 tree/layout/_partial/sidebar.ejs 文件，改下面部分

```
<!-- 按 tile ascii 排序 -->
input.sort(function(a, b){
	var len = a.title.length <= b.title.length ? a.title.length : b.title.length;
	for ( var i = 0; i < len; i++ ) {
		res = a.title[i].charCodeAt() - b.title[i].charCodeAt();
		if ( res ) { return res }
	}
	if(a.title.length <= b.title.length){
		return true;
	}else{
		return false;
	}
});
```

**Comment by qs-lll** [comment]
> 排序有个小 bug，改了
> 
> 你说的 demo 是指啥？主体下载下来就能用啊…… @qs-lll
demo指完整的  ,编译之前的,因为hexo默认分类是通过标签来控制的,你的分类是通过文件夹控制的,这个分类我搞了很久才明白

**Comment by wujun234** [comment]
> 
> 
> > 排序有个小 bug，改了
> > 你说的 demo 是指啥？主体下载下来就能用啊…… @qs-lll
> > demo指完整的  ,编译之前的,因为hexo默认分类是通过标签来控制的,你的分类是通过文件夹控制的,这个分类我搞了很久才明白

这个在 readme 的第五点有说明啊

**Comment by qs-lll** [comment]
> > > 排序有个小 bug，改了
> > > 你说的 demo 是指啥？主体下载下来就能用啊…… @qs-lll
> > > demo指完整的  ,编译之前的,因为hexo默认分类是通过标签来控制的,你的分类是通过文件夹控制的,这个分类我搞了很久才明白
> 
> 这个在 readme 的第五点有说明啊

对不起  我错了  没看文档..

**Comment by chinobing** [comment]
> > > 排序有个小 bug，改了
> > > 你说的 demo 是指啥？主体下载下来就能用啊…… @qs-lll
> > 
> > 
> > 文章或文件夹排序是根据什么来决定的？能改不？
> 
> 按 tile ascii 排序的，要修改去 tree/layout/_partial/sidebar.ejs 文件，改下面部分
> 
> ```
> 
> input.sort(function(a, b){
> 	var len = a.title.length <= b.title.length ? a.title.length : b.title.length;
> 	for ( var i = 0; i < len; i++ ) {
> 		res = a.title[i].charCodeAt() - b.title[i].charCodeAt();
> 		if ( res ) { return res }
> 	}
> 	if(a.title.length <= b.title.length){
> 		return true;
> 	}else{
> 		return false;
> 	}
> });
> ```

```
<!-- 按 post创建时间 排序 -->
	input.sort(function(a, b){
		res = b.post.date - a.post.date;
		return res
	});
});
``
