### ISSUE TITLE
想问个问题，如果节点也想作为文件可展示，有办法吗

### ISSUE THREAD

**Issue by GarfieldLucy** [wujun234/hexo-theme-tree#30]

**Comment by wujun234** [comment]
什么意思？我这里节点是文件夹。
你可以看一下生成目录树的js，如果你想用特定文件作为节点，可以修改一下那里

**Comment by GarfieldLucy** [comment]
啊好的，我这边就是不存在 folder 的概念，所有的都是文件，只是有层级好像是装在某个目录下的那种&nbsp;&nbsp;不晓得怎么实现比较合理难过



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WuJun"<notifications@github.com&gt;; 
发送时间: 2021年1月22日(星期五) 晚上8:02
收件人: "wujun234/hexo-theme-tree"<hexo-theme-tree@noreply.github.com&gt;; 
抄送: "扭蛋"<1020462958@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wujun234/hexo-theme-tree] 想问个问题，如果节点也想作为文件可展示，有办法吗 (#30)





 
什么意思？我这里节点是文件夹。
 你可以看一下生成目录树的js，如果你想用特定文件作为节点，可以修改一下那里

**Comment by wujun234** [comment]
目录不就是文件夹么？
