### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by jdccccc** [wujun234/hexo-theme-tree#33]
吴先生您好，我查看到您的图片都放置在imges文件夹中
但是在我在编辑Markdown语言时使用的是Typora工具
由于本主题的树结构是由文件夹关系体现的，所以Md文件与images文件夹的关系不确定
我不知道如何快捷的在任意一个文件夹目录下通过相对路径引用图片，请问您能提供一个方法吗
目前我已经尝试了assert选项的方法但是无济于事

**Comment by wujun234** [comment]
`![image](/images/1564648978779.jpg)`
我是使用这种方式引用的，可能本地编辑器看不了，但是转换成网页是可以的

**Comment by seekstar** [comment]
可以安装hexo-asset-image-fixed来将本地图片的路径转换成博客网站里的图片的路径，本地编辑器和网页上都工作正常。详细教程：<https://seekstar.github.io/2021/11/16/hexo%E6%8F%92%E5%85%A5%E5%9B%BE%E7%89%87/>

**Comment by wujun234** [comment]
https://github.com/wujun234/hexo-theme-tree#%E5%9B%BE%E7%89%87

我后面换 picgo 了，感觉也挺好用的

![image](https://user-images.githubusercontent.com/7530593/143028049-fca18458-7231-4fef-80d2-98a79501f026.png)

**Comment by jdccccc** [comment]
嗯嗯嗯，现在我也换成PicGO+Github图床了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月23日(星期二) 晚上8:58
收件人: "wujun234/hexo-theme-tree";
抄送: "Author";
主题: Re: [wujun234/hexo-theme-tree] 图片显示问题 (#33)





 
https://github.com/wujun234/hexo-theme-tree#%E5%9B%BE%E7%89%87
 
我后面换 picgo 了，感觉也挺好用的
 

 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
