### ISSUE TITLE
老哥，能否支持全局字体设置呢？

### ISSUE THREAD

**Issue by arashrun** [wujun234/hexo-theme-tree#36]
好像hexo本身没有一个自己的字体设置配置。

**Comment by wujun234** [comment]
这个改css里的字体就好了吧？
/source/css/main.css
font-family

**Comment by arashrun** [comment]
> 这个改css里的字体就好了吧？
> /source/css/main.css
> font-family

嗯嗯，修改好了。

**Comment by arashrun** [comment]
可以根据font-family的调用不同字体的优先级实现对中英文设置不同字体，设置时将英文字体放在前，中文字体放在后
