### ISSUE TITLE
怎么才能生成目录树？

### ISSUE THREAD

**Issue by ioxera** [wujun234/hexo-theme-tree#38]
怎样命名source文件夹里的文件夹名和文章的文件名才能生成目录树呢？

**Comment by wujun234** [comment]
正常命名啊，_posts 文件夹下的是 hexo 的发布文章

**Comment by ioxera** [comment]
OK，明白了，直接在_posts文件夹里面创建目录结构，我以为_posts目录里只能直接放文章呢，多谢指导

**Comment by ioxera** [comment]
我的_posts目录树和侧边栏如下，并没有显示出目录树
![截图_2021-08-25_20-25-27](https://user-images.githubusercontent.com/22150551/130790980-357d7507-291b-487b-b41e-bb988160a56a.png)
![截图_2021-08-25_20-32-39](https://user-images.githubusercontent.com/22150551/130791291-34e076de-6727-4336-86c1-4bc304e8b683.png)

**Comment by ioxera** [comment]
ok，解决了
1. _config.yml中的new_post_name值需要设置为“:title.md”，在文件名中添加日期会导致路径错误
2. relative_link:需要设置为“:false"来保证侧边目录导航正常
3. permalink设置为”:title“使生成的目录结构是_posts中设置的目录结构划分的而不是以日期为路径划分
