### ISSUE TITLE
站内引用失败

### ISSUE THREAD

**Issue by chinobing** [wujun234/hexo-theme-tree#4]
```
{% post_link “洗股“让上市公司高管避税减持 %}
```

因为sidebar的目录生成是根据folder和里面的md文章生成的，`post_link `是hexo的自带function，不知道是不是中文的原因， 没有显示。

**Comment by wujun234** [comment]
> 
> 
> ```
> {% post_link “洗股“让上市公司高管避税减持 %}
> ```
> 
> 因为sidebar的目录生成是根据folder和里面的md文章生成的，`post_link `是hexo的自带function，不知道是不是中文的原因， 没有显示。

我看了官方文档，[Hexo 标签插件#引用文章](https://hexo.io/zh-cn/docs/tag-plugins.html#%E5%BC%95%E7%94%A8%E6%96%87%E7%AB%A0)，这个跟我 sidebar 的生成是没有关系的，你考虑下你是否有名字叫 ` “洗股“让上市公司高管避税减持` 的 md 文件，里面的那个引号是否需要转义@chinobing

**Comment by chinobing** [comment]
> 
> 
> > ```
> > {% post_link “洗股“让上市公司高管避税减持 %}
> > ```
> > 
> > 
> > 因为sidebar的目录生成是根据folder和里面的md文章生成的，`post_link `是hexo的自带function，不知道是不是中文的原因， 没有显示。
> 
> 我看了官方文档，[Hexo 标签插件#引用文章](https://hexo.io/zh-cn/docs/tag-plugins.html#%E5%BC%95%E7%94%A8%E6%96%87%E7%AB%A0)，这个跟我 sidebar 的生成是没有关系的，你考虑下你是否有名字叫 ` “洗股“让上市公司高管避税减持` 的 md 文件，里面的那个引号是否需要转义@chinobing

应该与转义无关，因为我测试过其他纯中文title，都是一样情况。 我的另外一个blog用next theme，不过md文件都是英文title的就没有问题。

**Comment by wujun234** [comment]
> 
> 
> > > ```
> > > {% post_link “洗股“让上市公司高管避税减持 %}
> > > ```
> > > 
> > > 
> > > 因为sidebar的目录生成是根据folder和里面的md文章生成的，`post_link `是hexo的自带function，不知道是不是中文的原因， 没有显示。
> > 
> > 
> > 我看了官方文档，[Hexo 标签插件#引用文章](https://hexo.io/zh-cn/docs/tag-plugins.html#%E5%BC%95%E7%94%A8%E6%96%87%E7%AB%A0)，这个跟我 sidebar 的生成是没有关系的，你考虑下你是否有名字叫 ` “洗股“让上市公司高管避税减持` 的 md 文件，里面的那个引号是否需要转义@chinobing
> 
> 应该与转义无关，因为我测试过其他纯中文title，都是一样情况。 我的另外一个blog用next theme，不过md文件都是英文title的就没有问题。

我也没搞明白，试了英文的文件名也没引用成功，youtube  的标签都可以引用，不知道出了什么问题，如果你解决了麻烦在这里说一声

**Comment by chinobing** [comment]
行，那这个issue暂时不close

**Comment by chinobing** [comment]
已经从其他issues确认了，是hexo本身不支持subfolder结构。

**Comment by seekstar** [comment]
现在好像支持subfolder了？反正我现在用的hexo 6.0.0是可以站内引用subfolder下的博客的。

**Comment by seekstar** [comment]
中英文都可以：

{% post_link vscode/'vscode Couldn‘t start client Rust Language Server' %}

{% post_link vscode/'vscode在符号链接中转到定义打开了真实目录下的文件' %}

**Comment by chinobing** [comment]
谢哈，有空试试
