### ISSUE TITLE
左侧导航栏无法实时更新

### ISSUE THREAD

**Issue by zhangly-basefx** [wujun234/hexo-theme-tree#40]
作者你好，表示非常喜欢这个主题。
今天找了一下午，树状结构非常适合来记笔记。

这里有两个问题想请教一下：
1.点击文章后，左侧导航栏无法实时定位到文章位置。
需要再次刷新后，才会在左侧导航栏中定位到文章，并显示出文章的大纲视图。
我是在本地localhost测试的，清理过缓存也试过。没有找到什么原因导致的。

2.文章标题是不是只能修改文章的md文件命名。
下面的title字段是不是无法影响到文章名。

```
---
title: Deadline 使用技巧
date: 2020-11-21 17:17:02
---
```

因为新建文章的时候，用的是英文，然后出来为文章名就是这样的
![image](https://user-images.githubusercontent.com/21253510/142876302-14c03080-d5fc-475e-a11c-8e5c2a004bef.png)

空了回复我一下就好，谢谢啦

**Comment by seekstar** [comment]
第一个问题我也有。

关于第二个问题，你用的是最新版的主题吗？好像以前的版本是用文件名作为标题的。最近作者好像修复了这个问题。

**Comment by zhangly-basefx** [comment]
> 

我今天才pull下来的 应该是最新的版本的主题。

**Comment by seekstar** [comment]
这就很奇怪了。能把你的博客代码开源一下，让我看看吗？

顺便，我的博客代码在这：<https://gitee.com/searchstar/blog>

你也可以对比一下，看看是不是哪里配置错了。

**Comment by zhangly-basefx** [comment]
@seekstar 
我还没有部署到github page，我先参考参考你的吧。
第二个问题还好，大不了改成中文名。

第一个问题比较关键，比较影响浏览体验。

**Comment by seekstar** [comment]
等一下，我发现我这导航栏里的标题也是文件名，但是主页右边的标题是正常的。估计是作者修复了主页右边的标题显示，但是忘了把导航栏里的也一起修复了。

**Comment by zhangly-basefx** [comment]
@seekstar 
我自己研究了一下（不会ejs，会一点py编程大概看懂一些）

第二个问题可以修改这个文件
themes/tree/layout/_partial/sidebar.ejs
大概69行：
把
```
<%- node.title %>
```
修改为
```
<%- node.post.title %>
```
然后就好了。

**Comment by seekstar** [comment]
提个PR？

**Comment by zhangly-basefx** [comment]
@seekstar 
修改后，然后第一个问题也好了。
真是奇怪 哈哈哈

**Comment by wujun234** [comment]
最近加班太多了没时间看，晚上抽空看一眼

**Comment by wujun234** [comment]
1.点击文章后，左侧导航栏无法实时定位到文章位置。
这个我试了下，是可以的，可能是js加载的问题
2.文章标题是不是只能修改文章的md文件命名。
<img width="735" alt="image" src="https://user-images.githubusercontent.com/7530593/142962514-79a54d10-0cd0-448d-906d-8cb231d12ac3.png">
这个是故意保留的，想要文件名前面的序号来控制顺序，我看看加个可选项吧

**Comment by wujun234** [comment]
/themes/tree/_config.yml 新增配置项 sidebar.usePostTitle，可以了

<img width="733" alt="image" src="https://user-images.githubusercontent.com/7530593/142963768-9a23daef-6b6c-4011-8334-f2cef304a8e1.png">

**Comment by zhangly-basefx** [comment]
@wujun234 
感谢作者，暂时用来没什么问题了。
