### ISSUE TITLE
用了hexo-renderer-pandoc之后代码的基础色变成蓝色了

### ISSUE THREAD

**Issue by seekstar** [wujun234/hexo-theme-tree#41]
[我之前为了能正常显示Latex公式，安装了hexo-renderer-pandoc](https://seekstar.github.io/2021/11/16/hexo%E6%94%AF%E6%8C%81latex%E9%A3%8E%E6%A0%BC%E7%9A%84%E5%85%AC%E5%BC%8F%E7%BC%96%E8%BE%91/)。公式虽然能正常显示了，但是代码的基础色从白色变成蓝色了。因为底是黑色的，所以非常难看。我在tree主题里的layout/_partial/head.ejs里把

```js
<%- css('https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.17.1/build/styles/darcula.min.css') %>
```

改成

```js
<%- css('https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.17.1/build/styles/github.min.css') %>
```

之后，姑且把底换成浅灰色了，但是代码基础色还是蓝色的，理想状态应该是黑色。请问这个现象跟这个主题的配色有关系吗？

ps: 要是可以直接用pandoc里的highlight就好了。我在本地用pandoc的默认highlight方案生成的html非常好看。

**Comment by seekstar** [comment]
而且好像只有指定了语言的代码块的基础色才会变成蓝色。没有指定语言的代码块的基础色就很好看，黑底的话就是白色，白底的话就是黑色。

**Comment by wujun234** [comment]
跟主题应该没关系，主题没涉及代码块，可能跟 hexo 上用的哪个 highlight 插件有关系吧，你试下改hexo目录下的配置呢
<img width="899" alt="image" src="https://user-images.githubusercontent.com/7530593/143412883-bbafad55-44ce-4c1e-a21e-f407812595ce.png">

**Comment by wujun234** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/7530593/143412971-b4fd9528-2aa9-412e-b853-53934253216e.png">

话说，你们怎么都不改 favicon.ico 的，每次打开都有乱入的感觉 😂

**Comment by seekstar** [comment]
已经把自带的关掉了。如果开了的话，就用的默认的高亮。自带的有毛病，有时候会把行内代码变成行间代码，然后全部乱掉。

关于favicon.ico，我找到合适的就换 /笑哭

**Comment by seekstar** [comment]
更新到hexo 6.0.0就正常了。
