### ISSUE TITLE
左侧导航栏无法弹出

### ISSUE THREAD

**Issue by zhangly-basefx** [wujun234/hexo-theme-tree#43]
作者您好，今天发现左侧的导航栏无法弹出了。
看起来是因为dns污染，导致无法访问 https://cdn.jsdelivr.net 中的一个css资源
（我尝试过如果挂上代理，就没有问题了）

我想请问一下，这个 https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.17.1/build/styles/darcula.min.css
是否可以将它本地化。

![p1](https://user-images.githubusercontent.com/21253510/146719257-3c6edd7f-d12d-4257-bed5-c0068180ba2e.jpg)

**Comment by wujun234** [comment]
所有 css、js 都可以本地化，用 jsdelivr 只是考虑 github 容易被墙想用来加速

**Comment by zhangly-basefx** [comment]
感谢回复。

我自己是半个程序员，但是对css不太了解。
问下如果本地化，是不是将对应css地址的代码复制，替换本地中的css路径就好？
本地化难度大吗，如果还好的话，我自己试试。

因为很喜欢这个主题，不想因为这个问题而换其它的。

**Comment by wujun234** [comment]
本地化挺简单的，你看tree主题里本来就有自己本地的css、js

你可以把目标文件下载到本地，放在tree主题的css目录里，类似截图里这样替换引用就好

![image](https://user-images.githubusercontent.com/7530593/146723353-20e2eedb-66e4-4e11-9bde-61224dcd61b9.png)

**Comment by zhangly-basefx** [comment]
谢谢作者，我晚点试试。

万分感激！！

**Comment by seekstar** [comment]
太坑了。我刚刚研究了半天为什么会出这个问题，还以为是我markdown文档写错了。本地化之后能不能弄个PR并入主线？感觉大家都能用上。

**Comment by wujun234** [comment]
为啥 jsdelivr 也能被墙…

**Comment by zhangly-basefx** [comment]
@wujun234 
不知道，就挺意外的。
github+jsdelivr的方案估计不行了，之前博客+图床都是走的这个。

**Comment by zhangly-basefx** [comment]
@seekstar 
哈哈 又是你。等晚点我试了再说吧，也得争取下作者同意。

**Comment by seekstar** [comment]
@zhangly-basefx 对，又是我 /斜眼笑
确实要争取作者同意。提PR是对你说的，并入主线是对作者说的，没想到吧hhh

**Comment by wujun234** [comment]
我新push了一版，加了配置项里加了 `useLocalJsCss` 可选项，为本地试了ok，你们可以试试

**Comment by wujun234** [comment]
> github+jsdelivr的方案估计不行了

@zhangly-basefx 我看也有人部署在 gitee 上的，没用过，这个应该不会被墙

**Comment by seekstar** [comment]
> 我看也有人部署在 gitee 上的，没用过，这个应该不会被墙

gitee有自动审核，然后我的博客不知道为啥自动审核没过。。。而且我刚刚看了一下，我部署在gitee上的那个版本现在也是左侧导航栏无法弹出的状态。

**Comment by wujun234** [comment]
> > 我看也有人部署在 gitee 上的，没用过，这个应该不会被墙
> 
> gitee有自动审核，然后我的博客不知道为啥自动审核没过。。。而且我刚刚看了一下，我部署在gitee上的那个版本现在也是左侧导航栏无法弹出的状态。

gitee只能保证你站点能打开，js还是用jsdelivr加载的，依然被墙，你换useLocalJsCss为true就可以用本地js，就不会被墙了

**Comment by zhangly-basefx** [comment]
@wujun234 
谢谢作者，作者太快了哈哈哈！
我一会试试，应该没啥问题的。

gitee我没用过（界面不喜），
打算自建个gitlab，代码图床博客什么的都放上面得了。

**Comment by zhangly-basefx** [comment]
我刚刚试了，好像没成功。
这次的error没太看懂，不是很着急，作者空了看看就好。

![Snipaste_2021-12-20_15-55-46](https://user-images.githubusercontent.com/21253510/146732193-016b0618-6a76-4387-b126-0f6b304a0905.jpg)

**Comment by wujun234** [comment]
我先回滚，晚点再看

**Comment by zhangly-basefx** [comment]
好的 我现在空了 按照你说的自己改下试试。

**Comment by zhangly-basefx** [comment]
我刚刚试过了，直接替换成本地是ok的。
但是有个问题是一些图标消失了，我看到这里好像也引用了个什么文件。
作者有时间看看吧，实在是能力有限不懂css的语法。

![image](https://user-images.githubusercontent.com/21253510/146744959-4a871c6e-1d54-4e13-ac3c-8fa274b37f74.png)

**Comment by bearcai** [comment]
> 我刚刚试过了，直接替换成本地是ok的。 但是有个问题是一些图标消失了，我看到这里好像也引用了个什么文件。 作者有时间看看吧，实在是能力有限不懂css的语法。
> 
> ![image](https://user-images.githubusercontent.com/21253510/146744959-4a871c6e-1d54-4e13-ac3c-8fa274b37f74.png)

跟你一样情况下到本地，展开图标和缩回图标都挂了，看不出文件夹有没有展开了，解决了没/(ㄒoㄒ)/~~

**Comment by bearcai** [comment]
> > 我刚刚试过了，直接替换成本地是ok的。 但是有个问题是一些图标消失了，我看到这里好像也引用了个什么文件。 作者有时间看看吧，实在是能力有限不懂css的语法。
> > ![image](https://user-images.githubusercontent.com/21253510/146744959-4a871c6e-1d54-4e13-ac3c-8fa274b37f74.png)
> 
> 跟你一样情况下到本地，展开图标和缩回图标都挂了，看不出文件夹有没有展开了，解决了没/(ㄒoㄒ)/~~

解决了，`font-awesome.min.css`没有用`jsdelivr`，不修改就好了

**Comment by wujun234** [comment]
主要是 jsdelivr 被墙了，把用到 jsdelivr 的地方，换成其他 cdn 就可以解决了 @bearcai
