### ISSUE TITLE
侧边栏分类sidebar.ejs

### ISSUE THREAD

**Issue by 1021331023** [wujun234/hexo-theme-tree#46]
能看一下您https://wujun234.com/这个博客里的sidebar.ejs文件吗？我也想将侧边栏弄成按类别进行分类的格式。

**Comment by wujun234** [comment]
就在这个仓库里啊，这个就是主题

**Comment by 1021331023** [comment]
我是想要将左侧导航栏/文章树，按照“categories”进行分类

**Comment by 1021331023** [comment]
哦哦，我知道了，原来是要设置new_post_name: :title.md
