### ISSUE TITLE
生成静态文件异常

### ISSUE THREAD

**Issue by huangyang0517** [wujun234/hexo-theme-tree#49]
生成静态文件后，样式没了

**Comment by wujun234** [comment]
具体一点呢？听起来像是js文件在国内被屏蔽了，可以手动换一下

**Comment by lingyunfx** [comment]
我今天也遇到这个问题了，hexo g生成静态文件，然后用nginx去代理访问public文件夹里的index.html，出来的样式都丢失了。 应该跟js国内屏蔽没有关系，猜测是生成静态文件后，可能某些路径没对？
![image](https://user-images.githubusercontent.com/73666629/183564255-94d9c081-3e29-4986-9466-0bae2289c236.png)
