### ISSUE TITLE
做成一个npm包？

### ISSUE THREAD

**Issue by seekstar** [wujun234/hexo-theme-tree#52]
很多主题都做成了npm包，`npm install`一下就行，非常方便。`hexo-theme-tree`可以也做成一个npm包吗？

**Comment by wujun234** [comment]
我对前端不是很熟，不会做 npm 包， 你可以自己玩玩

**Comment by seekstar** [comment]
不行啊，我要是publish了npm包，那我就成上游了🤣

**Comment by wujun234** [comment]
可以研究下，好久没碰这块了😅
