### ISSUE TITLE
这个Hexo主题很漂亮和实用，能增加以下两个功能吗？

### ISSUE THREAD

**Issue by lthcweb** [wujun234/hexo-theme-tree#57]
这个Hexo主题很漂亮和实用，第一眼就喜欢上了。
能增加以下两个功能吗？谢谢 
1、giscus评论系统，
2、流程图时序图。

**Comment by wujun234** [comment]
短时间内应该不会有什么变动了，如果不是bug的话。你可以试着加一下哦。

**Comment by wujun234** [comment]
#59
