### ISSUE TITLE
分类和标签页面问题

### ISSUE THREAD

**Issue by brickunity** [wujun234/hexo-theme-tree#58]
按照步骤部署后，标签的页面显示不出标签的标识和统计只显示文章，而分类的页面则是空白，并报错no layout，有时甚至不报错，但就是空白的。检查过很多遍也查了很多次，请问要如何解决？

**Comment by wujun234** [comment]
目前看分类是正常的？而且这块是hexo实现的，跟tree主题没关系的，主题没修改这些部分
https://bricktotree.com/categories
![image](https://user-images.githubusercontent.com/7530593/216753479-9b24601e-0836-49a5-a6ca-109e0728c0cc.png)
