### ISSUE TITLE
markdown代码块识别问题

### ISSUE THREAD

**Issue by upheart-man** [wujun234/hexo-theme-tree#6]
只有代码块识别不出来，markdown插件已经安装，没做其他配置修改 @wujun234 ，老哥可以看看
![image](https://user-images.githubusercontent.com/22961574/77054110-4b136180-6a0a-11ea-9482-2c3989d27d89.png)

**Comment by wujun234** [comment]
你这个代码块是用什么写的？我的用 ``` 包裹的可以展示呀？
![image](https://user-images.githubusercontent.com/7530593/77131857-3a113180-6a98-11ea-8c94-638ef23729ad.png)

**Comment by wujun234** [comment]
https://www.upheart.top/2020/03/19/Redis/%E9%9B%86%E7%BE%A4/
这个是你的网站吧？我看代码块没问题呀？
![image](https://user-images.githubusercontent.com/7530593/77132072-084c9a80-6a99-11ea-98b7-136edbedafcf.png)

**Comment by wujun234** [comment]
还有你牛客网上说的“树形结构会乱”是指的什么呢？我看着没乱呀，这个是按你标题级别缩进的

![image](https://user-images.githubusercontent.com/7530593/77132129-40ec7400-6a99-11ea-9d48-50186b9d1734.png)

**Comment by upheart-man** [comment]
嗯嗯，我今天弄好了，是以下原因:
1.你的主题和hexo自带的主题冲突了，所以代码块没能识别，需要配置:highlighted:false
2.目录结构混乱是因为我电脑浏览器的缓存问题，清了下缓存就好了
最后感谢大佬的回答！

**Comment by upheart-man** [comment]
嗯嗯，我今天弄好了，是以下原因:
1.你的主题和hexo自带的主题冲突了，所以代码块没能识别，需要配置:highlighted:false
2.目录结构混乱是因为我电脑浏览器的缓存问题，清了下缓存就好了
最后感谢大佬的回答！ @wujun234

**Comment by wujun234** [comment]
谢谢，我 readme 补充一下

**Comment by Wanger-SJTU** [comment]
@xiaoflyfish 代码块的问题怎么解决的啊
