### ISSUE TITLE
没有title的文件，生成时会出错。

### ISSUE THREAD

**Issue by lthcweb** [wujun234/hexo-theme-tree#60]
如google\baidu的收录验证文件，googlexxxxxxxxxxxxxxxxx.html里面就一行代码，还不能改。
最好是放在source/下面，但生成时会出错。

**Comment by wujun234** [comment]
我看了下，我的  googlexxxxxxxxxxxxxxxxx.html 是放在 themes/tree/source 下面的

**Comment by seekstar** [comment]
放在`source/`下面，然后在`_config.yml`里写上`skip_render: googlexxxxxxxxx.html`。

**Comment by wujun234** [comment]
我没有碰到报错的情况诶，你这个 source 是指的哪个呢，hexo的？

**Comment by seekstar** [comment]
对，是hexo博客根目录下的`source/`，`_config.yml`也是hexo博客根目录下的。好像`source/`下的都会render，如果不写`skip_render`确实会报错。这个`skip_render`是之前在一个英文问答网站上看到的，现在已经找不到了/笑哭
放到`themes/tree/source`下面的话就不能用原滋原味的`hexo-theme-tree`了。如果`hexo-theme-tree`更新了，合并更改可能会有点麻烦。

**Comment by wujun234** [comment]
如果你放在 hexo 的 source 下面，就跟主题没关系了。我目前放主题下面，然后git忽略了没有上传
