### ISSUE TITLE
有几个优化建议~

### ISSUE THREAD

**Issue by walking-with-linght** [wujun234/hexo-theme-tree#62]
1左侧导航栏的排序规则是什么~
2主页设置某一文章的内容改怎么设置呢，就是访问 xx.com进去展示就是具体的某一文件的内容，现在是几篇文章的汇总展示。

**Comment by walking-with-linght** [comment]
另外，导航栏点击一下 页面全部就刷新了，可否修改为 只刷新文章，不刷新导航栏，，多点几下头要晕了

**Comment by walking-with-linght** [comment]
已转战gitbook。。。

**Comment by wujun234** [comment]
Gitbook 挺好的，我也在用
