### ISSUE TITLE
这个主题真的很棒！

### ISSUE THREAD

**Issue by X2ISPANDA** [wujun234/hexo-theme-tree#63]
大佬做的这个树基本解决了我的痛点，找了半天找到了您这个超棒的主题，但是我又不能舍弃butterfly带来的便捷和美观十分可惜，hexo的categories真的就是依托答辩，和tag没有本质区别。

**Comment by wujun234** [comment]
谢谢，你也可以直接将生成目录树的 js 拷贝到你的主题

**Comment by X2ISPANDA** [comment]
哈哈，主要咱们的代码水平太low了，就是个爱捣鼓的小辣鸡哈哈
