### ISSUE TITLE
valine 评论系统失效

### ISSUE THREAD

**Issue by shuoma4** [wujun234/hexo-theme-tree#64]

**Comment by wujun234** [comment]
来点上下文?

**Comment by shuoma4** [comment]
没啥上下文，就是有界面，但是评论服务不可用，不能发，也看不到评论区

**Comment by shuoma4** [comment]
我看网上的说法有改Js代码的，有改yaml文件中valine配置中severURLs字段的，但是我发现这个主题里面好像都没有

**Comment by shuoma4** [comment]
https://blog.yidaozhan.top/2021/12/19/valine-fix/

**Comment by wujun234** [comment]
主题里引用的已经是最新版js了，可以看 https://valine.js.org/changelog.html，valine 应该是没维护了，推荐你用 giscus，有评论还能通知你。

如果你的是这个文章里的问题，可以按照着文章里的说明，自行修改一下 JS 或者替换为文章中提供的那个 JS
