### ISSUE TITLE
缺少 Meta Description 标记

### ISSUE THREAD

**Issue by awaae001** [wujun234/hexo-theme-tree#65]
![image](https://github.com/wujun234/hexo-theme-tree/assets/108462724/4dadf304-3ef7-4447-8005-2509f61118ca)

在网站生成的时候添加 Meta Description 标记

**Comment by wujun234** [comment]
这个你要在 hexo 的 _config.yml 配置 keywords，tree 主题是支持的
![image](https://github.com/wujun234/hexo-theme-tree/assets/7530593/0026ab66-cbf7-4b01-952d-f593cda14171)
![image](https://github.com/wujun234/hexo-theme-tree/assets/7530593/e0f07836-0c83-446b-adfb-b40b23a5421a)

**Comment by awaae001** [comment]
但是我希望能够为每一个页面单独配置关键词。

**Comment by wujun234** [comment]
行吧，给你加一个

**Comment by awaae001** [comment]
谢谢大佬

**Comment by wujun234** [comment]
hello 我试了下，现在也是支持的，你在 post 上面加上 description
![image](https://github.com/wujun234/hexo-theme-tree/assets/7530593/fe575e5f-7154-4585-a4de-1c10bb785bdc)
![image](https://github.com/wujun234/hexo-theme-tree/assets/7530593/56dad39a-b5e4-47d3-a39c-1e24aedfe541)

**Comment by awaae001** [comment]
谢谢大佬，那个灯笼我自己研究一下
