### ISSUE TITLE
配置about页面报错

### ISSUE THREAD

**Issue by Qin0821** [wujun234/hexo-theme-tree#8]
我看大佬在about目录下面的index.html来写about页面，参考readme我在如下目录增加index.html文件，但是一直报错，请问是哪里搞错了吗？
![截屏2020-04-07 下午3 32 34](https://user-images.githubusercontent.com/25655555/78642296-13028e80-78e5-11ea-9c2f-422f24d3fffd.png)
![image](https://user-images.githubusercontent.com/25655555/78642362-32012080-78e5-11ea-9a18-622166330a13.png)

**Comment by wujun234** [comment]
你的 about 页是用命令建的还是复制的？我把当时的建 about 页的命令补充上去了

https://github.com/wujun234/hexo-theme-tree#4-about-%E9%A1%B5

Qin <notifications@github.com> 于2020年4月7日周二 下午3:36写道：

**Comment by Qin0821** [comment]
多谢大佬🙏
我之前是直接复制过去的
换了命令之后一下就好了😄
